service: controversies-of-science-feeds-api

frameworkVersion: ">=1.1.0 <2.0.0"

# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-west-1
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  # 'iamRoleStatement' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

# - authorizer: authenticate using the AWS IAM role
functions:
  create:
    handler: feeds/create.create
    events:
      - http:
          path: feeds/{cardSlug}
          method: post
          cors: true
          # authorizer: aws_iam
  get:
    handler: feeds/get.get
    events:
      - http:
          path: feeds/{cardSlug}/{feedSlug}
          method: get
          cors: true
          # authorizer: aws_iam
  slugs:
    handler: feeds/slugs.get
    events:
      - http:
          path: feeds/{cardSlug}
          method: get
          cors: true
          # authorizer: aws_iam
  delete:
    handler: feeds/delete.del
    events:
      - http:
          path: feeds/{cardSlug}/{feedSlug}
          method: delete
          cors: true
          # authorizer: aws_iam
  update:
    handler: feeds/update.update
    events:
      - http:
          path: feeds/{cardSlug}/{feedSlug}
          method: put
          cors: true
          # authorizer: aws_iam

resources:
  Resources:
    ControversyDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: cardSlug
            AttributeType: S
          - AttributeName: feedSlug
            AttributeType: S
        KeySchema:
          - AttributeName: cardSlug
            KeyType: HASH
          - AttributeName: feedSlug
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
